-- Долги клиентов: продажи с оплатой «Расчётный счёт» по клубной карте.
-- В отчётах такая продажа остаётся оплаченной, а долг ведётся отдельно в customer_debts.
-- Уже применено в Supabase; файл хранится для истории и переустановки.
create table if not exists public.customer_debts(
  id bigint generated by default as identity primary key,
  sale_id bigint not null unique references public.sales(id) on delete cascade,
  customer_id uuid not null references public.loyalty_customers(id),
  amount numeric(12,2) not null check(amount>0),
  created_at timestamptz not null default now(),
  paid_at timestamptz
);
create index if not exists customer_debts_customer_idx on public.customer_debts(customer_id);
-- Прямого доступа к таблице нет (RLS без политик): только через функции ниже.
alter table public.customer_debts enable row level security;

-- Долг создаётся автоматически, когда в продаже с клубной картой есть оплата «Расчётный счёт»
-- (в том числе частью раздельной оплаты).
create or replace function public.customer_debts_from_payment() returns trigger
language plpgsql security definer set search_path to 'public' as $fn$
declare v_customer uuid;
begin
  if new.payment_method<>'bank_account' then return new; end if;
  select loyalty_customer_id into v_customer from public.sales where id=new.sale_id;
  if v_customer is null then return new; end if;
  insert into public.customer_debts(sale_id,customer_id,amount) values(new.sale_id,v_customer,new.amount)
  on conflict(sale_id) do update set amount=public.customer_debts.amount+excluded.amount;
  return new;
end $fn$;
drop trigger if exists customer_debts_from_payment on public.sale_payments;
create trigger customer_debts_from_payment after insert on public.sale_payments
for each row execute function public.customer_debts_from_payment();

-- Список долгов (возвращённые продажи не показываются).
create or replace function public.debts_list(p_include_paid boolean default false)
returns table(debt_id bigint, sale_id bigint, order_number bigint, sale_created_at timestamptz, branch_name text, employee_name text,
  customer_id uuid, customer_name text, customer_phone text, amount numeric, sale_total numeric, paid_at timestamptz, items text)
language sql stable security definer set search_path to 'public' as $fn$
  select d.id, s.id, s.order_number, s.created_at, b.name, e.name, c.id, c.name, c.phone, d.amount, s.total, d.paid_at,
    (select string_agg(i.item_name||' × '||trim(to_char(i.quantity,'FM999999990.###')),', ' order by i.id) from public.sale_items i where i.sale_id=s.id)
  from public.customer_debts d
  join public.sales s on s.id=d.sale_id
  join public.loyalty_customers c on c.id=d.customer_id
  left join public.sales_branches b on b.id=s.branch_id
  left join public.sales_employees e on e.id=s.employee_id
  where s.status='completed' and (p_include_paid or d.paid_at is null)
  order by c.name, s.created_at;
$fn$;

-- Отметить оплаченными (сотрудники и администратор).
create or replace function public.debts_mark_paid(p_debt_ids bigint[]) returns integer
language plpgsql security definer set search_path to 'public' as $fn$
declare v_count integer;
begin
  update public.customer_debts set paid_at=now() where id=any(p_debt_ids) and paid_at is null;
  get diagnostics v_count=row_count; return v_count;
end $fn$;

-- Вернуть в долг ошибочно отмеченную продажу — только администратор.
create or replace function public.debts_mark_unpaid(p_debt_ids bigint[]) returns integer
language plpgsql security definer set search_path to 'public' as $fn$
declare v_count integer;
begin
  if coalesce(auth.role(),'')<>'authenticated' then raise exception 'Вернуть в долг может только администратор'; end if;
  update public.customer_debts set paid_at=null where id=any(p_debt_ids) and paid_at is not null;
  get diagnostics v_count=row_count; return v_count;
end $fn$;
grant execute on function public.debts_list(boolean), public.debts_mark_paid(bigint[]), public.debts_mark_unpaid(bigint[]) to anon, authenticated;
