-- Касса v5: оплата при получении, наличные в кассе, тесты по справочникам, объявления, сводка для админа.
-- Уже применено в Supabase; файл хранится для истории и переустановки.

-- ============ 1. Оплата при получении ============
-- Заказ «при получении» — это отложенная продажа: позиции и номер заказа сохранены, но в продажи и отчёты
-- она не попадает, пока клиент не оплатит. При оплате создаётся обычная продажа в текущей смене.
create table if not exists public.pickup_orders(
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.sales_branches(id),
  shift_id bigint references public.sales_shifts(id) on delete set null,
  employee_id bigint references public.sales_employees(id) on delete set null,
  order_number bigint,
  items jsonb not null,
  gross_total numeric(12,2) not null,
  discount_percent numeric not null default 0,
  total numeric(12,2) not null,
  customer_id uuid references public.loyalty_customers(id),
  client_name text,
  client_phone text,
  comment text,
  status text not null default 'pending' check (status in ('pending','paid','cancelled')),
  created_at timestamptz not null default now(),
  paid_at timestamptz,
  paid_shift_id bigint references public.sales_shifts(id) on delete set null,
  sale_id bigint references public.sales(id) on delete set null,
  cancelled_at timestamptz,
  cancel_reason text
);
create index if not exists pickup_orders_pending_idx on public.pickup_orders(branch_id, created_at) where status='pending';
alter table public.pickup_orders enable row level security;
create policy pickup_orders_read on public.pickup_orders for select to anon, authenticated using (true);

-- Отложить продажу «при получении». Возвращает номер заказа.
create or replace function public.sales_hold_pickup(p_shift_id bigint, p_employee_id bigint, p_items jsonb,
  p_discount_percent numeric default 0, p_comment text default null, p_order_number bigint default null,
  p_customer_id uuid default null, p_client_name text default null, p_client_phone text default null)
returns bigint language plpgsql security definer set search_path to 'public' as $fn$
declare v_shift public.sales_shifts%rowtype; v_item jsonb; v_cat public.sales_catalog%rowtype;
  v_qty numeric(12,3); v_price numeric(12,2); v_line numeric(12,2); v_gross numeric(12,2):=0; v_total numeric(12,2);
  v_items jsonb:='[]'::jsonb; v_min bigint; v_order bigint;
begin
  select * into v_shift from public.sales_shifts where id=p_shift_id and status='open' for update;
  if not found then raise exception 'Смена не найдена или уже закрыта'; end if;
  if not exists(select 1 from public.sales_shift_employees where shift_id=p_shift_id and employee_id=p_employee_id) then raise exception 'Сотрудник не подключён к этой смене'; end if;
  if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception 'Добавьте хотя бы одну позицию'; end if;
  if coalesce(p_discount_percent,0)<0 or coalesce(p_discount_percent,0)>100 then raise exception 'Скидка должна быть от 0 до 100%%'; end if;
  for v_item in select * from jsonb_array_elements(p_items) loop
    select * into v_cat from public.sales_catalog where id=(v_item->>'catalog_id')::bigint and is_active=true;
    if not found then raise exception 'Товар или услуга не найдены'; end if;
    v_qty:=coalesce((v_item->>'quantity')::numeric,0); v_price:=coalesce((v_item->>'unit_price')::numeric,v_cat.price);
    if v_qty<=0 or v_price<0 then raise exception 'Некорректное количество или цена'; end if;
    v_line:=round(v_qty*v_price,2); v_gross:=v_gross+v_line;
    v_items:=v_items||jsonb_build_array(jsonb_build_object('catalog_id',v_cat.id,'name',v_cat.name,'item_type',v_cat.item_type,'quantity',v_qty,'unit_price',v_price,'line_total',v_line));
  end loop;
  v_total:=round(v_gross-round(v_gross*coalesce(p_discount_percent,0)/100,2),2);
  -- Номер заказа берём из того же счётчика филиала, что и обычные продажи, и сразу резервируем.
  insert into public.sales_branch_order_counters(branch_id,next_number) values(v_shift.branch_id,1000) on conflict(branch_id) do nothing;
  select next_number into v_min from public.sales_branch_order_counters where branch_id=v_shift.branch_id for update;
  select greatest(v_min, coalesce(max(s.order_number)+1,v_min)) into v_min from public.sales s where s.branch_id=v_shift.branch_id;
  v_order:=case when p_order_number is null or p_order_number<v_min then v_min else p_order_number end;
  while exists(select 1 from public.sales s where s.branch_id=v_shift.branch_id and s.order_number=v_order)
     or exists(select 1 from public.pickup_orders o where o.branch_id=v_shift.branch_id and o.order_number=v_order and o.status='pending') loop
    v_order:=v_order+1;
  end loop;
  update public.sales_branch_order_counters set next_number=greatest(next_number,v_order+1),updated_at=now() where branch_id=v_shift.branch_id;
  insert into public.pickup_orders(branch_id,shift_id,employee_id,order_number,items,gross_total,discount_percent,total,customer_id,client_name,client_phone,comment)
  values(v_shift.branch_id,v_shift.id,p_employee_id,v_order,v_items,v_gross,coalesce(p_discount_percent,0),v_total,p_customer_id,
    nullif(trim(coalesce(p_client_name,'')),''),nullif(trim(coalesce(p_client_phone,'')),''),nullif(trim(coalesce(p_comment,'')),''));
  return v_order;
end $fn$;

-- Список заказов «при получении» с именами клиентов и сотрудников.
create or replace function public.pickup_list(p_branch_id bigint default null, p_include_closed boolean default false)
returns table(id bigint, branch_id bigint, branch_name text, order_number bigint, items jsonb, gross_total numeric, discount_percent numeric,
  total numeric, customer_id uuid, customer_name text, customer_phone text, client_name text, client_phone text, comment text,
  employee_name text, status text, created_at timestamptz, paid_at timestamptz, cancelled_at timestamptz, cancel_reason text)
language sql stable security definer set search_path to 'public' as $fn$
  select o.id,o.branch_id,b.name,o.order_number,o.items,o.gross_total,o.discount_percent,o.total,o.customer_id,c.name,c.phone,
    o.client_name,o.client_phone,o.comment,coalesce(p.name,e.name),o.status,o.created_at,o.paid_at,o.cancelled_at,o.cancel_reason
  from public.pickup_orders o
  left join public.sales_branches b on b.id=o.branch_id
  left join public.loyalty_customers c on c.id=o.customer_id
  left join public.sales_employees e on e.id=o.employee_id
  left join public.sales_people p on p.id=e.person_id
  where (p_branch_id is null or o.branch_id=p_branch_id)
    and (o.status='pending' or (p_include_closed and coalesce(o.paid_at,o.cancelled_at)>now()-interval '30 days'))
  order by o.created_at;
$fn$;

create or replace function public.sales_cancel_pickup(p_pickup_id bigint, p_reason text default null) returns boolean
language plpgsql security definer set search_path to 'public' as $fn$
begin
  update public.pickup_orders set status='cancelled',cancelled_at=now(),cancel_reason=nullif(trim(coalesce(p_reason,'')),'')
  where id=p_pickup_id and status='pending';
  if not found then raise exception 'Заказ не найден или уже закрыт'; end if;
  return true;
end $fn$;

-- Обычная продажа. Изменения: учитывает номера, зарезервированные заказами «при получении»,
-- и при оплате такого заказа оставляет его номер (через polaroid.pickup_order).
CREATE OR REPLACE FUNCTION public.sales_create_sale(p_shift_id bigint, p_employee_id bigint, p_payment_method text, p_comment text, p_items jsonb, p_loyalty_customer_id uuid DEFAULT NULL::uuid, p_loyalty_points numeric DEFAULT 0, p_loyalty_name text DEFAULT NULL::text, p_loyalty_phone text DEFAULT NULL::text, p_loyalty_comment text DEFAULT NULL::text, p_order_number bigint DEFAULT NULL::bigint, p_discount_percent numeric DEFAULT 0, p_payments jsonb DEFAULT '[]'::jsonb)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_shift public.sales_shifts%rowtype;
  v_sale_id bigint;
  v_order bigint;
  v_gross numeric(12,2):=0;
  v_discount numeric(12,2):=0;
  v_after_discount numeric(12,2):=0;
  v_total numeric(12,2):=0;
  v_points numeric(12,2):=round(coalesce(p_loyalty_points,0),2);
  v_item jsonb; v_pay jsonb; v_catalog public.sales_catalog%rowtype;
  v_qty numeric(12,3); v_price numeric(12,2); v_line numeric(12,2);
  v_pay_sum numeric(12,2):=0; v_customer_id uuid:=p_loyalty_customer_id;
  v_min bigint;
  v_forced bigint:=nullif(current_setting('polaroid.pickup_order',true),'')::bigint;
begin
  select * into v_shift from public.sales_shifts where id=p_shift_id and status='open' for update;
  if not found then raise exception 'Смена не найдена или уже закрыта'; end if;
  if not exists(select 1 from public.sales_shift_employees where shift_id=p_shift_id and employee_id=p_employee_id) then raise exception 'Сотрудник не подключён к этой смене'; end if;
  if p_payment_method not in ('cash','card','qr','link','bank_account','transfer','split') then raise exception 'Выберите способ оплаты'; end if;
  if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception 'Добавьте хотя бы одну позицию'; end if;
  if coalesce(p_discount_percent,0)<0 or coalesce(p_discount_percent,0)>100 then raise exception 'Скидка должна быть от 0 до 100%%'; end if;

  for v_item in select * from jsonb_array_elements(p_items) loop
    select * into v_catalog from public.sales_catalog where id=(v_item->>'catalog_id')::bigint and is_active=true;
    if not found then raise exception 'Товар или услуга не найдены'; end if;
    v_qty:=coalesce((v_item->>'quantity')::numeric,0); v_price:=coalesce((v_item->>'unit_price')::numeric,v_catalog.price);
    if v_qty<=0 or v_price<0 then raise exception 'Некорректное количество или цена'; end if;
    v_line:=round(v_qty*v_price,2); v_gross:=v_gross+v_line;
  end loop;
  v_discount:=round(v_gross*coalesce(p_discount_percent,0)/100,2);
  v_after_discount:=round(v_gross-v_discount,2);
  if v_points<0 or v_points>round(v_after_discount*0.30,2) then raise exception 'Баллами можно оплатить не более 30%% после скидки'; end if;
  if v_points>0 then
    if v_customer_id is null then raise exception 'Выберите клиента клубной карты'; end if;
    perform public.loyalty_redeem(v_customer_id,v_after_discount,v_points,'Списание баллов при продаже');
  end if;
  v_total:=round(v_after_discount-v_points,2);

  if p_payment_method='split' then
    if jsonb_typeof(p_payments)<>'array' or jsonb_array_length(p_payments)<2 then raise exception 'Для раздельной оплаты добавьте минимум два способа оплаты'; end if;
    for v_pay in select * from jsonb_array_elements(p_payments) loop
      if (v_pay->>'method') not in ('cash','card','qr','link','bank_account','transfer') then raise exception 'Некорректный способ в раздельной оплате'; end if;
      if coalesce((v_pay->>'amount')::numeric,0)<=0 then raise exception 'Сумма каждого способа оплаты должна быть больше 0'; end if;
      v_pay_sum:=v_pay_sum+round((v_pay->>'amount')::numeric,2);
    end loop;
  else
    v_pay_sum:=v_total;
  end if;
  if round(v_pay_sum,2)<>round(v_total,2) then raise exception 'Сумма способов оплаты должна быть ровно %',v_total; end if;

  insert into public.sales_branch_order_counters(branch_id,next_number) values(v_shift.branch_id,1000) on conflict(branch_id) do nothing;
  select next_number into v_min from public.sales_branch_order_counters where branch_id=v_shift.branch_id for update;
  if v_forced is not null and v_forced=p_order_number
     and not exists(select 1 from public.sales s where s.branch_id=v_shift.branch_id and s.order_number=v_forced) then
    -- Оплата заказа «при получении»: номер был зарезервирован при оформлении.
    v_order:=v_forced;
  else
    select greatest(v_min, coalesce(max(s.order_number)+1,v_min)) into v_min
    from public.sales s where s.branch_id=v_shift.branch_id;
    v_order:=case when p_order_number is null or p_order_number<v_min then v_min else p_order_number end;
    while exists(select 1 from public.sales s where s.branch_id=v_shift.branch_id and s.order_number=v_order)
       or exists(select 1 from public.pickup_orders o where o.branch_id=v_shift.branch_id and o.order_number=v_order and o.status='pending') loop
      v_order:=v_order+1;
    end loop;
  end if;

  if v_customer_id is null and nullif(trim(coalesce(p_loyalty_phone,'')),'') is not null then
    select x.customer_id into v_customer_id from public.loyalty_add_purchase(trim(p_loyalty_name),trim(p_loyalty_phone),v_gross,nullif(trim(coalesce(p_loyalty_comment,'')),'')) x limit 1;
  elsif v_customer_id is not null then
    select x.customer_id into v_customer_id from public.loyalty_customers c cross join lateral public.loyalty_add_purchase(c.name,c.phone,v_gross,nullif(trim(coalesce(p_loyalty_comment,'')),'')) x where c.id=v_customer_id;
  end if;

  insert into public.sales(order_number,shift_id,branch_id,employee_id,payment_method,total,gross_total,discount_percent,discount_amount,loyalty_points_used,loyalty_customer_id,comment,receipt_issued,payment_status,paid_at)
  values(v_order,v_shift.id,v_shift.branch_id,p_employee_id,p_payment_method,v_total,v_gross,coalesce(p_discount_percent,0),v_discount,v_points,v_customer_id,nullif(trim(coalesce(p_comment,'')),''),case when p_payment_method='link' then null else true end,case when p_payment_method='link' then 'pending' else 'paid' end,case when p_payment_method='link' then null else now() end)
  returning id into v_sale_id;

  for v_item in select * from jsonb_array_elements(p_items) loop
    select * into v_catalog from public.sales_catalog where id=(v_item->>'catalog_id')::bigint;
    v_qty:=(v_item->>'quantity')::numeric; v_price:=(v_item->>'unit_price')::numeric; v_line:=round(v_qty*v_price,2);
    insert into public.sale_items(sale_id,catalog_id,item_type,item_name,quantity,unit_price,line_total,cost_price,cost_total)
    values(v_sale_id,v_catalog.id,v_catalog.item_type,v_catalog.name,v_qty,v_price,v_line,v_catalog.cost_price,round(coalesce(v_catalog.cost_price,0)*v_qty,2));
  end loop;
  if p_payment_method='split' then
    for v_pay in select * from jsonb_array_elements(p_payments) loop
      insert into public.sale_payments(sale_id,payment_method,amount) values(v_sale_id,(v_pay->>'method'),round((v_pay->>'amount')::numeric,2));
    end loop;
  else
    insert into public.sale_payments(sale_id,payment_method,amount) values(v_sale_id,p_payment_method,v_total);
  end if;
  update public.sales_branch_order_counters set next_number=greatest(next_number,v_order+1),updated_at=now() where branch_id=v_shift.branch_id;
  return v_order;
end; $function$;

-- Клиент пришёл и оплатил заказ «при получении»: создаём обычную продажу в текущей смене с тем же номером.
create or replace function public.sales_pay_pickup(p_pickup_id bigint, p_shift_id bigint, p_employee_id bigint, p_payment_method text,
  p_comment text, p_items jsonb, p_loyalty_customer_id uuid default null, p_loyalty_points numeric default 0,
  p_loyalty_name text default null, p_loyalty_phone text default null, p_loyalty_comment text default null,
  p_discount_percent numeric default 0, p_payments jsonb default '[]'::jsonb)
returns bigint language plpgsql security definer set search_path to 'public' as $fn$
declare v_o public.pickup_orders%rowtype; v_order bigint; v_branch bigint; v_sale bigint;
begin
  select * into v_o from public.pickup_orders where id=p_pickup_id for update;
  if not found or v_o.status<>'pending' then raise exception 'Заказ уже оплачен или отменён'; end if;
  select branch_id into v_branch from public.sales_shifts where id=p_shift_id;
  perform set_config('polaroid.pickup_order',case when v_branch=v_o.branch_id then v_o.order_number::text else '' end,true);
  v_order:=public.sales_create_sale(p_shift_id,p_employee_id,p_payment_method,p_comment,p_items,p_loyalty_customer_id,p_loyalty_points,
    p_loyalty_name,p_loyalty_phone,p_loyalty_comment,case when v_branch=v_o.branch_id then v_o.order_number else null end,p_discount_percent,p_payments);
  perform set_config('polaroid.pickup_order','',true);
  select id into v_sale from public.sales where branch_id=v_branch and order_number=v_order order by id desc limit 1;
  update public.pickup_orders set status='paid',paid_at=now(),paid_shift_id=p_shift_id,sale_id=v_sale where id=p_pickup_id;
  return v_order;
end $fn$;

grant execute on function public.sales_hold_pickup(bigint,bigint,jsonb,numeric,text,bigint,uuid,text,text),
  public.pickup_list(bigint,boolean), public.sales_cancel_pickup(bigint,text),
  public.sales_pay_pickup(bigint,bigint,bigint,text,text,jsonb,uuid,numeric,text,text,text,numeric,jsonb) to anon, authenticated;

-- ============ 2. Наличные в кассе ============
alter table public.sales_shifts add column if not exists open_cash numeric(12,2);
alter table public.sales_shifts add column if not exists open_cash_expected numeric(12,2);
alter table public.sales_shifts add column if not exists open_cash_at timestamptz;
alter table public.sales_shifts add column if not exists open_cash_employee_id bigint references public.sales_employees(id) on delete set null;
alter table public.sales_shifts add column if not exists close_cash numeric(12,2);
alter table public.sales_shifts add column if not exists close_cash_employee_id bigint references public.sales_employees(id) on delete set null;

-- Сколько должно быть в кассе: остаток, который указали при закрытии последней смены филиала.
create or replace function public.sales_shift_cash_info(p_shift_id bigint) returns jsonb
language sql stable security definer set search_path to 'public' as $fn$
  select jsonb_build_object('shiftId',s.id,'openCash',s.open_cash,'openCashExpected',s.open_cash_expected,'closeCash',s.close_cash,
    'cashSales',(select coalesce(sum(p.amount),0) from public.sale_payments p join public.sales x on x.id=p.sale_id
                 where x.shift_id=s.id and x.status='completed' and p.payment_method='cash'),
    'prev',(select jsonb_build_object('shiftId',v.id,'closeCash',v.close_cash,'endedAt',v.ended_at,
              'closedBy',(select coalesce(pp.name,e.name) from public.sales_employees e left join public.sales_people pp on pp.id=e.person_id where e.id=v.close_cash_employee_id))
            from public.sales_shifts v where v.branch_id=s.branch_id and v.id<>s.id and v.status='closed' and v.close_cash is not null
            order by v.ended_at desc nulls last limit 1))
  from public.sales_shifts s where s.id=p_shift_id;
$fn$;

create or replace function public.sales_set_open_cash(p_shift_id bigint, p_employee_id bigint, p_amount numeric) returns boolean
language plpgsql security definer set search_path to 'public' as $fn$
declare v_expected numeric(12,2); v_branch bigint;
begin
  if p_amount is null or p_amount<0 then raise exception 'Укажите сумму наличных в кассе'; end if;
  select branch_id into v_branch from public.sales_shifts where id=p_shift_id and status='open';
  if not found then raise exception 'Смена не найдена или уже закрыта'; end if;
  if not exists(select 1 from public.sales_shift_employees where shift_id=p_shift_id and employee_id=p_employee_id) then raise exception 'Сотрудник не участвует в смене'; end if;
  select close_cash into v_expected from public.sales_shifts where branch_id=v_branch and id<>p_shift_id and status='closed' and close_cash is not null order by ended_at desc nulls last limit 1;
  update public.sales_shifts set open_cash=round(p_amount,2),open_cash_expected=v_expected,open_cash_at=now(),open_cash_employee_id=p_employee_id where id=p_shift_id;
  return true;
end $fn$;

create or replace function public.sales_set_close_cash(p_shift_id bigint, p_employee_id bigint, p_amount numeric) returns boolean
language plpgsql security definer set search_path to 'public' as $fn$
begin
  if p_amount is null or p_amount<0 then raise exception 'Укажите остаток наличных в кассе'; end if;
  if not exists(select 1 from public.sales_shift_employees se join public.sales_shifts s on s.id=se.shift_id
                where se.shift_id=p_shift_id and se.employee_id=p_employee_id and s.status='open') then
    raise exception 'Смена закрыта или сотрудник не участвует в смене'; end if;
  update public.sales_shifts set close_cash=round(p_amount,2),close_cash_employee_id=p_employee_id where id=p_shift_id;
  return true;
end $fn$;
grant execute on function public.sales_shift_cash_info(bigint), public.sales_set_open_cash(bigint,bigint,numeric), public.sales_set_close_cash(bigint,bigint,numeric) to anon, authenticated;

-- Закрытие смены требует указать остаток наличных (миграция kassa_v5_close_requires_cash, применена после выкладки сайта).
-- В public.sales_close_team_shift перед закрытием добавлена проверка:
--   if v_shift.close_cash is null then raise exception 'Укажите остаток наличных в кассе. Если окна для суммы нет — обновите страницу (Ctrl+F5).'; end if;

-- ============ 3. Тесты по справочникам ============
create table if not exists public.guide_questions(
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products(id) on delete cascade,
  question text not null,
  options jsonb not null,
  correct_index integer not null default 0,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists guide_questions_product_idx on public.guide_questions(product_id, sort_order);
alter table public.guide_questions enable row level security;
create policy guide_questions_read on public.guide_questions for select to anon, authenticated using (true);
create policy guide_questions_admin_insert on public.guide_questions for insert to authenticated with check (true);
create policy guide_questions_admin_update on public.guide_questions for update to authenticated using (true) with check (true);
create policy guide_questions_admin_delete on public.guide_questions for delete to authenticated using (true);

create table if not exists public.guide_test_results(
  id bigint generated by default as identity primary key,
  product_id uuid references public.products(id) on delete cascade,
  person_id bigint references public.sales_people(id) on delete set null,
  person_name text not null,
  score integer not null,
  total integer not null,
  wrong jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists guide_test_results_product_idx on public.guide_test_results(product_id, created_at desc);
alter table public.guide_test_results enable row level security;
create policy guide_test_results_read on public.guide_test_results for select to anon, authenticated using (true);
create policy guide_test_results_insert on public.guide_test_results for insert to anon, authenticated with check (score>=0 and total>0 and score<=total);
create policy guide_test_results_admin_delete on public.guide_test_results for delete to authenticated using (true);

-- ============ 4. Объявления ============
create table if not exists public.announcements(
  id bigint generated by default as identity primary key,
  title text not null,
  body text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.announcements enable row level security;
create policy announcements_read on public.announcements for select to anon, authenticated using (true);
create policy announcements_admin_insert on public.announcements for insert to authenticated with check (true);
create policy announcements_admin_update on public.announcements for update to authenticated using (true) with check (true);
create policy announcements_admin_delete on public.announcements for delete to authenticated using (true);

create table if not exists public.announcement_reads(
  announcement_id bigint not null references public.announcements(id) on delete cascade,
  person_id bigint not null references public.sales_people(id) on delete cascade,
  shift_id bigint references public.sales_shifts(id) on delete set null,
  read_at timestamptz not null default now(),
  primary key(announcement_id, person_id)
);
alter table public.announcement_reads enable row level security;
create policy announcement_reads_read on public.announcement_reads for select to anon, authenticated using (true);

-- Сотрудник подтверждает прочтение только из открытой смены, в которой работает.
create or replace function public.announcement_mark_read(p_announcement_id bigint, p_shift_id bigint, p_person_id bigint) returns boolean
language plpgsql security definer set search_path to 'public' as $fn$
begin
  if not exists(select 1 from public.sales_shift_employees se join public.sales_employees e on e.id=se.employee_id
                join public.sales_shifts s on s.id=se.shift_id
                where se.shift_id=p_shift_id and e.person_id=p_person_id and s.status='open') then
    raise exception 'Смена закрыта или сотрудник не участвует в смене'; end if;
  insert into public.announcement_reads(announcement_id,person_id,shift_id) values(p_announcement_id,p_person_id,p_shift_id)
  on conflict(announcement_id,person_id) do nothing;
  return true;
end $fn$;
grant execute on function public.announcement_mark_read(bigint,bigint,bigint) to anon, authenticated;

-- ============ 5. Сводка для администратора ============
-- Сводка: текущий период [p_from,p_to) сравнивается с периодом [p_prev_from,p_prev_to). Только для администратора.
create or replace function public.admin_period_summary(p_from timestamptz, p_to timestamptz, p_prev_from timestamptz, p_prev_to timestamptz,
  p_branch_id bigint default null, p_bucket text default 'day', p_tz text default 'Europe/Moscow') returns jsonb
language plpgsql stable security definer set search_path to 'public' as $fn$
declare v jsonb; v_step interval;
begin
  if coalesce(auth.role(),'')<>'authenticated' then raise exception 'Сводка доступна только администратору'; end if;
  if p_bucket not in ('hour','day','week','month') then raise exception 'Некорректная группировка'; end if;
  v_step:=('1 '||p_bucket)::interval;
  with s as (
    select x.*, case when x.created_at>=p_from and x.created_at<p_to then 'cur' else 'prev' end as per
    from public.sales x
    where ((x.created_at>=p_from and x.created_at<p_to) or (x.created_at>=p_prev_from and x.created_at<p_prev_to)) and x.status='completed' and x.payment_status<>'unpaid'
      and (p_branch_id is null or x.branch_id=p_branch_id)
  ), it as (
    select i.*, s.per, coalesce(nullif(c.category,''),'Без категории') as cat
    from public.sale_items i join s on s.id=i.sale_id left join public.sales_catalog c on c.id=i.catalog_id
  ), tot as (
    select per, sum(total) rev, count(*) cnt, sum(discount_amount) disc, sum(loyalty_points_used) pts,
      count(*) filter (where loyalty_customer_id is not null) club
    from s group by per
  ), costs as (select per, sum(coalesce(cost_total,0)) cost, count(*) filter (where cost_price is null) no_cost from it group by per),
  rets as (
    select case when r.created_at>=p_from and r.created_at<p_to then 'cur' else 'prev' end per, sum(r.amount) amt, count(*) cnt
    from public.sales_returns r where ((r.created_at>=p_from and r.created_at<p_to) or (r.created_at>=p_prev_from and r.created_at<p_prev_to)) and (p_branch_id is null or r.branch_id=p_branch_id) group by 1
  ), newc as (
    select case when c.created_at>=p_from and c.created_at<p_to then 'cur' else 'prev' end per, count(*) cnt
    from public.loyalty_customers c where (c.created_at>=p_from and c.created_at<p_to) or (c.created_at>=p_prev_from and c.created_at<p_prev_to) group by 1
  ), sh as (
    select case when x.started_at>=p_from and x.started_at<p_to then 'cur' else 'prev' end per, count(*) cnt
    from public.sales_shifts x where ((x.started_at>=p_from and x.started_at<p_to) or (x.started_at>=p_prev_from and x.started_at<p_prev_to)) and (p_branch_id is null or x.branch_id=p_branch_id) group by 1
  ), per_obj as (
    select p.per, jsonb_build_object('revenue',coalesce(t.rev,0),'count',coalesce(t.cnt,0),'discount',coalesce(t.disc,0),'points',coalesce(t.pts,0),
      'club',coalesce(t.club,0),'cost',coalesce(c.cost,0),'noCostItems',coalesce(c.no_cost,0),'returns',coalesce(r.amt,0),'returnsCount',coalesce(r.cnt,0),
      'newCustomers',coalesce(n.cnt,0),'shifts',coalesce(h.cnt,0)) o
    from (values('cur'),('prev')) p(per)
    left join tot t on t.per=p.per left join costs c on c.per=p.per left join rets r on r.per=p.per
    left join newc n on n.per=p.per left join sh h on h.per=p.per
  ), items as (
    select item_name name, max(cat) cat,
      sum(quantity) filter (where per='cur') qty, sum(line_total) filter (where per='cur') rev, sum(cost_total) filter (where per='cur') cost,
      sum(quantity) filter (where per='prev') pqty, sum(line_total) filter (where per='prev') prev
    from it group by item_name
  ), cats as (
    select cat name, sum(line_total) filter (where per='cur') rev, sum(line_total) filter (where per='prev') prev from it group by cat
  ), br as (
    select coalesce(b.name,'?') name, sum(s.total) filter (where per='cur') rev, count(*) filter (where per='cur') cnt,
      sum(s.total) filter (where per='prev') prev, count(*) filter (where per='prev') pcnt
    from s left join public.sales_branches b on b.id=s.branch_id group by 1
  ), em as (
    select coalesce(pp.name,e.name,'?') name, sum(s.total) filter (where per='cur') rev, count(*) filter (where per='cur') cnt,
      sum(s.total) filter (where per='prev') prev, count(*) filter (where per='prev') pcnt
    from s left join public.sales_employees e on e.id=s.employee_id left join public.sales_people pp on pp.id=e.person_id group by 1
  ), pay as (
    select p.payment_method m, sum(p.amount) filter (where s.per='cur') amt, sum(p.amount) filter (where s.per='prev') prev
    from public.sale_payments p join s on s.id=p.sale_id group by 1
  ), cur_b as (
    select g b from generate_series(date_trunc(p_bucket,p_from at time zone p_tz), (p_to at time zone p_tz)-interval '1 second', v_step) g
  ), prev_b as (
    select g b from generate_series(date_trunc(p_bucket,p_prev_from at time zone p_tz), (p_prev_to at time zone p_tz)-interval '1 second', v_step) g
  ), sb as (
    select per, date_trunc(p_bucket, created_at at time zone p_tz) b, sum(total) rev, count(*) cnt from s group by 1,2
  ), wd as (
    select extract(isodow from created_at at time zone p_tz)::int d, sum(total) rev, count(*) cnt from s where per='cur' group by 1
  ), hr as (
    select extract(hour from created_at at time zone p_tz)::int h, sum(total) rev, count(*) cnt from s where per='cur' group by 1
  ), cash as (
    select x.started_at, b.name branch, x.open_cash, x.open_cash_expected
    from public.sales_shifts x left join public.sales_branches b on b.id=x.branch_id
    where x.started_at>=p_from and x.started_at<p_to and (p_branch_id is null or x.branch_id=p_branch_id)
      and x.open_cash is not null and x.open_cash_expected is not null and x.open_cash<>x.open_cash_expected
  ), tests as (
    select r.product_id, p.name, count(*) cnt, round(avg(r.score*100.0/r.total)) pct
    from public.guide_test_results r left join public.products p on p.id=r.product_id
    where r.created_at>=p_from and r.created_at<p_to group by 1,2
  )
  select jsonb_build_object(
    'cur',(select o from per_obj where per='cur'),
    'prev',(select o from per_obj where per='prev'),
    'items',(select coalesce(jsonb_agg(jsonb_build_object('name',name,'cat',cat,'qty',coalesce(qty,0),'rev',coalesce(rev,0),'cost',coalesce(cost,0),'pqty',coalesce(pqty,0),'prev',coalesce(prev,0)) order by coalesce(rev,0) desc),'[]') from items),
    'cats',(select coalesce(jsonb_agg(jsonb_build_object('name',name,'rev',coalesce(rev,0),'prev',coalesce(prev,0)) order by coalesce(rev,0) desc),'[]') from cats),
    'branches',(select coalesce(jsonb_agg(jsonb_build_object('name',name,'rev',coalesce(rev,0),'cnt',cnt,'prev',coalesce(prev,0),'pcnt',pcnt) order by coalesce(rev,0) desc),'[]') from br),
    'employees',(select coalesce(jsonb_agg(jsonb_build_object('name',name,'rev',coalesce(rev,0),'cnt',cnt,'prev',coalesce(prev,0),'pcnt',pcnt) order by coalesce(rev,0) desc),'[]') from em),
    'payments',(select coalesce(jsonb_agg(jsonb_build_object('method',m,'amt',coalesce(amt,0),'prev',coalesce(prev,0)) order by coalesce(amt,0) desc),'[]') from pay),
    'series',(select coalesce(jsonb_agg(jsonb_build_object('b',to_char(cb.b,'YYYY-MM-DD"T"HH24:MI'),'rev',coalesce(x.rev,0),'cnt',coalesce(x.cnt,0)) order by cb.b),'[]') from cur_b cb left join sb x on x.per='cur' and x.b=cb.b),
    'prevSeries',(select coalesce(jsonb_agg(jsonb_build_object('b',to_char(pb.b,'YYYY-MM-DD"T"HH24:MI'),'rev',coalesce(x.rev,0),'cnt',coalesce(x.cnt,0)) order by pb.b),'[]') from prev_b pb left join sb x on x.per='prev' and x.b=pb.b),
    'weekdays',(select coalesce(jsonb_agg(jsonb_build_object('d',d,'rev',rev,'cnt',cnt) order by d),'[]') from wd),
    'hours',(select coalesce(jsonb_agg(jsonb_build_object('h',h,'rev',rev,'cnt',cnt) order by h),'[]') from hr),
    'cashIssues',(select coalesce(jsonb_agg(jsonb_build_object('at',started_at,'branch',branch,'actual',open_cash,'expected',open_cash_expected) order by started_at),'[]') from cash),
    'tests',(select coalesce(jsonb_agg(jsonb_build_object('name',name,'cnt',cnt,'pct',pct) order by pct),'[]') from tests),
    'pickups',(select jsonb_build_object('count',count(*),'sum',coalesce(sum(total),0),
        'overdue',count(*) filter (where created_at<now()-interval '2 days'),'overdueSum',coalesce(sum(total) filter (where created_at<now()-interval '2 days'),0))
      from public.pickup_orders where status='pending' and (p_branch_id is null or branch_id=p_branch_id)),
    'debts',(select coalesce(sum(d.amount),0) from public.customer_debts d join public.sales x on x.id=d.sale_id where d.paid_at is null and x.status='completed')
  ) into v;
  return v;
end $fn$;
grant execute on function public.admin_period_summary(timestamptz,timestamptz,timestamptz,timestamptz,bigint,text,text) to authenticated;

-- Старое имя оставлено как обёртка (предыдущий период — сразу перед текущим).
create or replace function public.admin_summary(p_from timestamptz, p_to timestamptz, p_prev_from timestamptz,
  p_branch_id bigint default null, p_bucket text default 'day', p_tz text default 'Europe/Moscow') returns jsonb
language sql stable security definer set search_path to 'public' as $fn$
  select public.admin_period_summary(p_from,p_to,p_prev_from,p_from,p_branch_id,p_bucket,p_tz);
$fn$;
