-- Задания на сотрудника (переходят на его следующую смену на любом филиале, пока не выполнены)
-- и ручной порядок справочников.

create table if not exists public.sales_person_tasks (
  id bigint generated by default as identity primary key,
  person_id bigint not null references public.sales_people(id) on delete cascade,
  title text not null,
  description text,
  start_date date not null default current_date,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  completed_shift_id bigint references public.sales_shifts(id) on delete set null,
  completed_by_employee_id bigint references public.sales_employees(id) on delete set null
);
create index if not exists sales_person_tasks_open_idx on public.sales_person_tasks(person_id) where completed_at is null and is_active;

alter table public.sales_person_tasks enable row level security;
create policy sales_person_tasks_read on public.sales_person_tasks for select to anon, authenticated using (true);
create policy sales_person_tasks_admin_insert on public.sales_person_tasks for insert to authenticated with check (true);
create policy sales_person_tasks_admin_update on public.sales_person_tasks for update to authenticated using (true) with check (true);
create policy sales_person_tasks_admin_delete on public.sales_person_tasks for delete to authenticated using (true);

-- Сотрудник отмечает своё задание выполненным только из открытой смены, в которой он участвует.
create or replace function public.sales_complete_person_task(p_task_id bigint, p_shift_id bigint, p_employee_id bigint)
returns void language plpgsql security definer set search_path = public as $$
declare v_person bigint;
begin
  select e.person_id into v_person
  from sales_shift_employees se
  join sales_employees e on e.id = se.employee_id
  join sales_shifts s on s.id = se.shift_id
  where se.shift_id = p_shift_id and se.employee_id = p_employee_id and s.ended_at is null;
  if v_person is null then raise exception 'Смена закрыта или сотрудник не участвует в смене'; end if;
  update sales_person_tasks
     set completed_at = now(), completed_shift_id = p_shift_id, completed_by_employee_id = p_employee_id
   where id = p_task_id and person_id = v_person and completed_at is null and is_active;
  if not found then raise exception 'Задание не найдено или уже выполнено'; end if;
end $$;
grant execute on function public.sales_complete_person_task(bigint, bigint, bigint) to anon, authenticated;

-- Ручной порядок справочников: заполненные идут первыми по возрастанию, остальные по алфавиту.
alter table public.products add column if not exists sort_order integer;
